# Generated by Django 4.2.7 on 2025-05-15 17:37

import cloudinary.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH_APP', 'Cash App'), ('PAYPAL', 'PayPal'), ('ZELLE', 'Zelle'), ('PIX', 'PIX')], max_length=10)),
                ('name_tag', models.CharField(help_text='Cash App Tag or PayPal/Zelle identifier', max_length=100)),
                ('qr_code_image', cloudinary.models.CloudinaryField(blank=True, default='None', max_length=255, null=True, verbose_name='image')),
                ('bank_image', cloudinary.models.CloudinaryField(blank=True, default='None', max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': '3- Aza Detail',
                'verbose_name_plural': '3-Aza Details',
            },
        ),
        migrations.CreateModel(
            name='CONTACT_US',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'CONTACT US',
                'verbose_name_plural': 'CONTACT US',
            },
        ),
        migrations.CreateModel(
            name='CRYPWALLETS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.CharField(blank=True, max_length=500, null=True)),
                ('bitcoin_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('ethereum', models.CharField(blank=True, max_length=500, null=True)),
                ('ethereum_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('usdt_erc20', models.CharField(blank=True, max_length=500, null=True)),
                ('usdt_erc20_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('tron', models.CharField(blank=True, max_length=500, null=True)),
                ('tron_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': '4- WALLETS',
                'verbose_name_plural': '4-WALLETS',
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('loan_product', models.CharField(choices=[('MORTGAGE', 'Residential Mortgage'), ('HELOC', 'Home Equity Line of Credit'), ('AUTO', 'Auto Loan'), ('PERSONAL', 'Personal Loan'), ('BUSINESS', 'Business Loan'), ('STUDENT', 'Student Loan'), ('CREDIT_BUILDER', 'Credit Builder Loan'), ('INVESTMENT', 'Investment Property Loan'), ('LINE_OF_CREDIT', 'Personal Line of Credit'), ('OVERDRAFT', 'Overdraft Protection')], max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term', models.CharField(choices=[('6M', '6 Months'), ('1Y', '1 Year'), ('2Y', '2 Years'), ('3Y', '3 Years'), ('5Y', '5 Years'), ('7Y', '7 Years'), ('10Y', '10 Years'), ('15Y', '15 Years'), ('20Y', '20 Years'), ('25Y', '25 Years'), ('30Y', '30 Years')], max_length=3)),
                ('rate_type', models.CharField(choices=[('FIXED', 'Fixed Rate'), ('VARIABLE', 'Variable Rate'), ('HYBRID', 'Hybrid Rate')], default='FIXED', max_length=10)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('purpose', models.TextField()),
                ('collateral_description', models.TextField(blank=True, null=True)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('existing_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled'), ('FUNDED', 'Funded')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('co_applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal_internationa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('recipient_bank_name', models.CharField(default='', max_length=200)),
                ('account_number', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals_international', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manage Transfer_international',
                'verbose_name_plural': 'Manage Transfers_international',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('bank_sort_code', models.CharField(default='', max_length=200)),
                ('swift_code', models.CharField(default='', max_length=200)),
                ('recipient_bank_name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=80)),
                ('account_number', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('approval_document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='approval_doc')),
                ('fee_receipt', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fee_receipt')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2 - Manage Transfer',
                'verbose_name_plural': '2 -Manage Transfers',
            },
        ),
        migrations.CreateModel(
            name='WiseWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wise_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wise_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SUPPORT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.CharField(choices=[('Please Select Customer Service Department', 'Please Select Customer Service Department'), ('My Account Is Suspended/Blocked', 'My Account Is Suspended/Blocked'), ('Customer Services Department', 'Customer Services Department'), ('Account Department', 'Account Department'), ('Transfer Department', 'Transfer Department'), ('Card Services Department', 'Card Services Department'), ('Loan Department', 'Loan Department'), ('Bank Deposit Department', 'Bank Deposit Department')], max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '6- SUPPORT',
                'verbose_name_plural': '6- SUPPORT',
            },
        ),
        migrations.CreateModel(
            name='SkrillWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skrill_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skrill_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevolutWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revolut_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revolut_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('USDT_TRC20', 'USDT TRC20'), ('ETHEREUM', 'Ethereum'), ('BITCOIN', 'Bitcoin'), ('GIFTCARD', 'Giftcard'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('giftcard_type', models.CharField(blank=True, choices=[('Select Giftcard', 'Select Giftcard'), ('APPLE', 'Apple'), ('GOOGLE', 'Google'), ('ITUNES', 'iTunes'), ('AMAZON', 'Amazon')], max_length=20, null=True)),
                ('giftcard_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bank_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.banktransfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1- Bank Deposit',
                'verbose_name_plural': '1- Bank Deposit',
            },
        ),
        migrations.CreateModel(
            name='PayBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=512)),
                ('address2', models.CharField(default='', max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=512)),
                ('zipcode', models.CharField(max_length=512)),
                ('nickname', models.CharField(max_length=512)),
                ('delivery_method', models.CharField(choices=[('Paper Check', 'Paper Check'), ('Digital Receipt', 'Digital Receipt')], default='', max_length=200)),
                ('memo', models.CharField(default='', max_length=80)),
                ('account_number', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('day', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '5-Manage Bills',
                'verbose_name_plural': '5-Manage Bills',
            },
        ),
        migrations.CreateModel(
            name='LocalWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_account_number', models.CharField(max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('LATE', 'Late'), ('MISSED', 'Missed')], default='SCHEDULED', max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.loanapplication')),
            ],
            options={
                'verbose_name': 'Loan Payment',
                'verbose_name_plural': 'Loan Payments',
                'ordering': ['payment_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID', 'Identification Document'), ('PROOF_OF_INCOME', 'Proof of Income'), ('BANK_STATEMENT', 'Bank Statement'), ('TAX_RETURN', 'Tax Return'), ('PROPERTY_DOCS', 'Property Documents'), ('COLLATERAL_DOCS', 'Collateral Documents'), ('BUSINESS_DOCS', 'Business Documents'), ('OTHER', 'Other Documents')], max_length=20)),
                ('document_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transactions.loanapplication')),
            ],
            options={
                'verbose_name': 'Loan Document',
                'verbose_name_plural': 'Loan Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWITHDRAW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('TRON', 'Tron'), ('ETHEREUM', 'Ethereum'), ('BITCOIN', 'Bitcoin')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recipient_address', models.CharField(default='', max_length=512)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2- Crypto Withdrawal',
                'verbose_name_plural': '2-Crypto Withdrawals',
            },
        ),
        migrations.CreateModel(
            name='CHECK_DEPOSIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='deposits/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='deposits/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check Deposit',
                'verbose_name_plural': 'Check Deposits',
            },
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('V', 'Visa'), ('M', 'Mastercard'), ('D', 'Discover'), ('A', 'American Express'), ('CUP', 'China Union Pay'), ('DC', 'Dollar Card'), ('MC', 'Master Card'), ('VC', 'Visa Card'), ('JC', 'JCB Card'), ('AE', 'American Express'), ('UB', 'Union Bank Card'), ('BC', 'Bank Card'), ('EB', 'Eurocard'), ('NC', 'Nordic Card'), ('AC', 'Asian Card'), ('IC', 'International Card'), ('MC', 'Maestro Card'), ('EC', 'Eurocheque Card'), ('GC', 'Global Card'), ('UC', 'Uba Card'), ('FC', 'First Bank Card'), ('ZC', 'Zenith Bank Card'), ('AC', 'Access Bank Card'), ('GC', 'GTBank Card'), ('KC', 'Keystone Bank Card'), ('EC', 'Ecobank Card'), ('IC', 'UBA International Card'), ('OC', 'Other Card')], max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('expiry_month', models.PositiveIntegerField()),
                ('expiry_year', models.PositiveIntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('card_owner', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Card',
                'verbose_name_plural': 'Client Cards',
            },
        ),
    ]
